### PR TITLE
feat: add toggle to control 4G+ feature

### LINKED ISSUE #31: Enable 5G, as well as 4G/4g+ icons
Hi, thank you for the module!

I noticed you are using the `telephony.ICarrierConfigLoader.overrideConfig()` which if I am correct, would be the equivalent of editing the carrier config xml file (?)

Would it be possible for you to extend the current script to include an option to 
a) choose to show 4g/4g+ icons instead of LTE icons, 
b) enable 5G if supported by operator
c) enable wifi calling if supported by operator

Perhaps the code below can be useful as an idea?

```
import android.os.RemoteException;
import android.telephony.CarrierConfigManager;
import android.telephony.TelephonyManager;
import android.util.Log;

import com.android.internal.telephony.ICarrierConfigLoader;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public class CarrierConfigOverrider {
    private static final String TAG = "CarrierConfigOverrider";

    public static void enableVolteAnd5G(TelephonyManager telephonyManager) {
        CarrierConfigManager configManager = (CarrierConfigManager) telephonyManager.getContext().getSystemService(Context.CARRIER_CONFIG_SERVICE);
        ICarrierConfigLoader configLoader = configManager.getConfigForSubId(telephonyManager.getSubId());
        if (configLoader == null) {
            Log.e(TAG, "Unable to get ICarrierConfigLoader");
            return;
        }

        try {
            Method method = configLoader.getClass().getDeclaredMethod("overrideConfig", int.class, PersistableBundle.class);
            method.setAccessible(true);

            PersistableBundle config = new PersistableBundle();
            config.putBoolean(CarrierConfigManager.KEY_VOLTE_VT_ENABLED_BOOL, true);
            config.putBoolean(CarrierConfigManager.KEY_CARRIER_ALLOW_METERED_ROAMING_BOOL, true);
            config.putString(CarrierConfigManager.KEY_PREFERRED_NETWORK_MODE_INT, Integer.toString(TelephonyManager.NETWORK_TYPE_NR));

            method.invoke(configLoader, telephonyManager.getSubId(), config);
        } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException e) {
            Log.e(TAG, "Unable to override carrier config", e);
        }
    }
}

```

I'm not so familiar with Android development, so sorry but I cannot contribute more code.

### PR DESCRIPTION
**Pull request by kyujin-cho**
This resolves #31.

### CODE REVIEW

**Comment by DarkSofter** [comment]
> This broke VoLTE for me. Wouldn't show in SIM settings and wouldn't work anymore.
> VoWiFi was still working.
> Had to clear al settings to fix it.

same, i have to keep it enabled in order for volte to work

**Comment by mpoozd** [comment]
> same, i have to keep it enabled in order for volte to work

Does 4g+/LTE+ break voLTE ?

**Comment by DarkSofter** [comment]
> 
> > same, i have to keep it enabled in order for volte to work
> 
> Does 4g+/LTE+ break voLTE ? 

i have enabled everything except hide enhanced data icon and volte works fine. if i disable the (untested) toggle ot breaks volte

**Comment by mpoozd** [comment]
> > > same, i have to keep it enabled in order for volte to work
> > 
> > 
> > Does 4g+/LTE+ break voLTE ?
> 
> i have enabled everything except hide enhanced data icon and volte works fine. if i disable the (untested) toggle ot breaks volte

I tried it and 4g+ doesn't work also it breaks volte even If I disabled enhanced data ..

**Comment by DarkSofter** [comment]
> > > > same, i have to keep it enabled in order for volte to work
> > > 
> > > 
> > > Does 4g+/LTE+ break voLTE ?
> > 
> > i have enabled everything except hide enhanced data icon and volte works fine. if i disable the (untested) toggle ot breaks volte
> 
> I tried it and 4g+ didn't work also it broke volte 

does your network have carrier aggregation? in any case, if volte worked for you in the previous versions, maybe just try using 1.1.x?

**Comment by kszaq** [comment]
Hi @kyujin-cho. This may be confusing but actually the setting does not control 4G+ feature but whether VoLTE switch is visible. I found this out because in latest A13 update, Google changed CarrierSettings for my carrier with `KEY_HIDE_ENHANCED_4G_LTE_BOOL = true`, it made VoLTE invisible with VoLTE still working.

**Pull request merged**
