### PR TITLE
feat: data icon toggles

### PR DESCRIPTION
**Pull request by eanavalentin**
Adds toggle between LTE/4G data icons
Adds toggle for showing enhanced (carrier aggregation - 4G+/LTE+) toggle

### CODE REVIEW

**Review by kyujin-cho — APPROVED** [review]
LGTM!

**Comment by jonkraja** [comment]
> LGTM!

will it be implemented in the next app version? can't wait!

**Comment by kyujin-cho** [comment]
@DarkSofter For sure.

**Comment by DarkSofter** [comment]
> @DarkSofter For sure.

Thanks a lot! 
# Now we wait impatiently hahha

**Comment by kyujin-cho** [comment]
@DarkSofter https://github.com/kyujin-cho/pixel-volte-patch/releases/tag/1.2.1 🎉

**Comment by DarkSofter** [comment]
> @DarkSofter https://github.com/kyujin-cho/pixel-volte-patch/releases/tag/1.2.1 

yayy!! i was waiting so impatiently for this. i hated the lte icon. you are doing gods work sir!

**Pull request merged**
