### PR TITLE
fix: disable config when failed to load the value

### LINKED ISSUE #70: App crashes on OnePlus 7 Pro with Android 12
Although the patch is intended for Pixel phones, there are reports of successful use for OnePlus devices on xda forums. 
However, the latest (1.2.2) version of the app crashes with NPE once I click icon of either sim cards on my OnePlus 7 Pro Android 12.
Crash log is attached: [crash_log.txt](https://github.com/kyujin-cho/pixel-volte-patch/files/10875505/crash_log.txt).

I was able to to launch v. 1.1.2 (but only got VoWifi option for the second sim, no VoLte/VoWifi shown for the first sim and no VoLte for the second sim).
If any additional info is required, please let me know.

### PR DESCRIPTION
**Pull request by kyujin-cho**
This fixes #70.

### CODE REVIEW

**Comment by kyujin-cho** [comment]
Can you test with if this patch resolves your issue? You can download the APK by clicking [here](https://github.com/kyujin-cho/pixel-volte-patch/files/10888526/app-debug.apk.zip).

**Comment by alex-x-x** [comment]
Thanks for the quick response!
I have just tried new apk, but got a crash again, here is the stacktrace:
```
03-04 17:15:05.509  1576  1576 E AndroidRuntime: FATAL EXCEPTION: main
03-04 17:15:05.509  1576  1576 E AndroidRuntime: Process: dev.bluehouse.enablevolte, PID: 1576
03-04 17:15:05.509  1576  1576 E AndroidRuntime: java.lang.NullPointerException: config.getString(key) must not be null
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at dev.bluehouse.enablevolte.SubscriptionModer.getStringValue(Moder.kt:149)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at dev.bluehouse.enablevolte.SubscriptionModer.getUserAgentConfig(Moder.kt:223)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at dev.bluehouse.enablevolte.pages.ConfigKt.Config$loadFlags(Config.kt:60)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at dev.bluehouse.enablevolte.pages.ConfigKt.access$Config$loadFlags(Config.kt:1)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at dev.bluehouse.enablevolte.pages.ConfigKt$Config$1.invoke(Config.kt:68)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at dev.bluehouse.enablevolte.pages.ConfigKt$Config$1.invoke(Config.kt:63)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at dev.bluehouse.enablevolte.ComponentsKt$OnLifecycleEvent$1$1$observer$1.onStateChanged(Components.kt:40)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at dev.bluehouse.enablevolte.ComponentsKt$OnLifecycleEvent$1$1.invoke(Components.kt:43)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at dev.bluehouse.enablevolte.ComponentsKt$OnLifecycleEvent$1$1.invoke(Components.kt:37)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1091)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:818)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:839)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:585)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:503)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1230)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:925)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:233)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:344)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8212)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
03-04 17:15:05.509  1576  1576 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@3450ac5, androidx.compose.ui.platform.MotionDurationScaleImpl@70bcc1a, StandaloneCoroutine{Cancelling}@e52034b, AndroidUiDispatcher@cee7128]
03-04 17:15:05.510  1966  3454 D OplusAppStartupMonitor: notifyUnstableAppInfo: Bundle[{unstableTime=1677939305510, reason=crash, userId=0, safecenter=unstable, exceptionMsg=config.getString(key) must not be null, exceptionClass=java.lang.NullPointerException, packageName=dev.bluehouse.enablevolte, unstable_restrict_switch=true}]
03-04 17:15:05.511  5528  3097 I Athena  : StartupManager: onUpdateUnstableRecord: unstable crash!
```

**Comment by kyujin-cho** [comment]
Oops, I forgot to add some critical lines :-( Can you try once more with [this](https://github.com/kyujin-cho/pixel-volte-patch/files/10888855/app-debug.apk.zip)?

**Comment by alex-x-x** [comment]
Thanks a lot for the quick fix! It stopped crashing and works for both sim cards now. 
 
Some additional feedback after checking the switchers:
- voLTE switcher for SIM1 is shown now. There is no voLTE switcher for SIM2 shown (I used to have it for Android 11 and it even worked! As far as I remember, it was in enabled state only in case I had 'Dual 4G networks' switcher turned on. But in Android 12 this switcher is absent at all.). 
- voWiFi switcher for SIM1 and SIM2 is shown now. 'WiFi Calling preferences' are also shown with options: 'Wi-Fi calling preferred'. 'Cellular calling preferred'. No specific options for Roaming are shown, though.
- voWiFi does not seem to work for my SIM1 (used to work on Android 11), for SIM2 it is disabled at operator's level so cannot check it. 

Not sure if it is possible to do anything about that, just wanted to share my findings :)

**Comment by kyujin-cho** [comment]
@alex-x-x Thanks for the feedback. I'll merge this PR for now discuss about those on a separate issue.

**Pull request merged**
