### PR TITLE
feat: ss over cdma

### PR DESCRIPTION
**Pull request by huajijam**
feat: ss_over_cdma

same as ss_over_ut, but for CDMA carrier

### CODE REVIEW

**Comment by kyujin-cho** [comment]
Uh... From my pure curiosity, is there a carrier actually utilizing CDMA services nowadays?

**Comment by huajijam** [comment]
> Uh... From my pure curiosity, is there a carrier actually utilizing CDMA services nowadays?

in china,yes (maybe?
just make it work,and it will work when ss over ut not work

**Review by kyujin-cho — APPROVED** [review]
LGTM! Please resolve merge conflicts.

**Comment by huajijam** [comment]
> LGTM! Please resolve merge conflicts.

done

**Pull request merged**
